# Generated by Django 3.2.3 on 2021-06-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_list', models.ManyToManyField(to='Hs.Card', verbose_name='卡牌列表')),
            ],
        ),
    ]
