# Generated by Django 3.2.3 on 2021-06-09 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('card_list', models.ManyToManyField(blank=True, null=True, to='Hs.Card', verbose_name='卡牌列表')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '卡牌收藏',
                'verbose_name_plural': '卡牌收藏',
            },
        ),
        migrations.AddConstraint(
            model_name='usercard',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='collection_minimum'),
        ),
    ]
