# Generated by Django 3.2.3 on 2021-06-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='card_list',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='summoner_class',
        ),
        migrations.RemoveField(
            model_name='deckcard',
            name='card',
        ),
        migrations.RemoveField(
            model_name='deckcard',
            name='deck',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Deck',
        ),
        migrations.DeleteModel(
            name='DeckCard',
        ),
    ]
