# Generated by Django 3.2.3 on 2021-06-10 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hs', '0002_auto_20210610_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='套牌id')),
                ('name', models.CharField(max_length=64, verbose_name='套牌名称')),
            ],
            options={
                'verbose_name': '套牌',
                'verbose_name_plural': '套牌',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testword', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hs.card', verbose_name='卡牌')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hs.deck', verbose_name='套牌')),
            ],
            options={
                'verbose_name': '套牌关系',
                'verbose_name_plural': '套牌关系',
            },
        ),
        migrations.AddField(
            model_name='deck',
            name='card_list',
            field=models.ManyToManyField(through='Hs.DeckCard', to='Hs.Card'),
        ),
        migrations.AddField(
            model_name='deck',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='拥有者'),
        ),
        migrations.AddField(
            model_name='deck',
            name='summoner_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hs.summonerclass', verbose_name='套牌职业'),
        ),
        migrations.AddConstraint(
            model_name='deckcard',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='card_minimum'),
        ),
    ]
