# Generated by Django 3.2.3 on 2021-06-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hs', '0002_card_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='img',
            field=models.ImageField(default='default.jpg', null=True, upload_to='card_img', verbose_name='图片'),
        ),
    ]
