# Generated by Django 3.2.3 on 2021-06-09 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hs', '0002_auto_20210609_1814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCard',
        ),
    ]
