# Generated by Django 3.2.3 on 2021-06-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hs', '0003_delete_deck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='套牌id')),
                ('name', models.CharField(max_length=64, verbose_name='套牌名称')),
                ('card_list', models.ManyToManyField(to='Hs.Card', verbose_name='卡牌列表')),
            ],
        ),
    ]
