# Generated by Django 3.2.3 on 2021-06-09 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hs', '0004_deck'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deck',
        ),
    ]
