# Generated by Django 3.2.3 on 2021-06-10 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hs', '0004_alter_deck_card_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_owner', to=settings.AUTH_USER_MODEL, verbose_name='拥有者'),
        ),
    ]
