# Generated by Django 3.2.3 on 2021-06-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hs', '0005_alter_deck_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='keyword',
            field=models.ManyToManyField(blank=True, null=True, related_name='card_keyword', to='Hs.Keyword', verbose_name='关键词'),
        ),
    ]
